# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

MOZBUILD_DERIVED := 1
DIRS := config editline shell
TEST_DIRS := jsapi-tests tests gdb
DEFINES += -DIMPL_MFBT -DEXPORT_JS_API
HOST_SIMPLE_PROGRAMS += host_jskwgen
HOST_SIMPLE_PROGRAMS += host_jsoplengen
LOCAL_INCLUDES += -I$(srcdir)/../../mfbt/double-conversion
CPPSRCS += ../../mfbt/Compression.cpp
CPPSRCS += ../../mfbt/decimal/Decimal.cpp
CPPSRCS += frontend/Parser.cpp
CPPSRCS += jsarray.cpp
CPPSRCS += jsatom.cpp
CPPSRCS += jsmath.cpp
CPPSRCS += jsutil.cpp
CPPSRCS += assembler/jit/ExecutableAllocatorPosix.cpp
CPPSRCS += yarr/OSAllocatorPosix.cpp
CPPSRCS += assembler/assembler/ARMAssembler.cpp
CPPSRCS += assembler/assembler/MacroAssemblerARM.cpp
CPPSRCS += assembler/assembler/MacroAssemblerX86Common.cpp
CPPSRCS += yarr/YarrJIT.cpp
CPPSRCS += perf/pm_stub.cpp
FORCE_SHARED_LIB := 1
FORCE_STATIC_LIB := 1
HOST_CPPSRCS += jskwgen.cpp
HOST_CPPSRCS += jsoplengen.cpp
MSVC_ENABLE_PGO := 1
CPPSRCS += ../../mfbt/FloatingPoint.cpp ../../mfbt/HashFunctions.cpp ../../mfbt/Poison.cpp ../../mfbt/SHA1.cpp ../../mfbt/double-conversion/bignum-dtoa.cc ../../mfbt/double-conversion/bignum.cc ../../mfbt/double-conversion/cached-powers.cc ../../mfbt/double-conversion/diy-fp.cc ../../mfbt/double-conversion/double-conversion.cc ../../mfbt/double-conversion/fast-dtoa.cc ../../mfbt/double-conversion/fixed-dtoa.cc ../../mfbt/double-conversion/strtod.cc assembler/jit/ExecutableAllocator.cpp builtin/Eval.cpp builtin/Intl.cpp builtin/MapObject.cpp builtin/Object.cpp builtin/ParallelArray.cpp builtin/Profilers.cpp builtin/RegExp.cpp builtin/TestingFunctions.cpp builtin/TypeRepresentation.cpp builtin/TypedObject.cpp devtools/sharkctl.cpp ds/LifoAlloc.cpp frontend/BytecodeCompiler.cpp frontend/BytecodeEmitter.cpp frontend/FoldConstants.cpp frontend/NameFunctions.cpp frontend/ParseMaps.cpp frontend/ParseNode.cpp frontend/TokenStream.cpp gc/Barrier.cpp gc/Iteration.cpp gc/Marking.cpp gc/Memory.cpp gc/Nursery.cpp gc/RootMarking.cpp gc/Statistics.cpp gc/StoreBuffer.cpp gc/Tracer.cpp gc/Verifier.cpp gc/Zone.cpp jit/AliasAnalysis.cpp jit/AsmJS.cpp jit/AsmJSLink.cpp jit/AsmJSModule.cpp jit/AsmJSSignalHandlers.cpp jit/BacktrackingAllocator.cpp jit/Bailouts.cpp jit/BaselineBailouts.cpp jit/BaselineCompiler.cpp jit/BaselineFrame.cpp jit/BaselineFrameInfo.cpp jit/BaselineIC.cpp jit/BaselineInspector.cpp jit/BaselineJIT.cpp jit/BitSet.cpp jit/BytecodeAnalysis.cpp jit/C1Spewer.cpp jit/CodeGenerator.cpp jit/CompileWrappers.cpp jit/EdgeCaseAnalysis.cpp jit/EffectiveAddressAnalysis.cpp jit/Ion.cpp jit/IonAnalysis.cpp jit/IonBuilder.cpp jit/IonCaches.cpp jit/IonFrames.cpp jit/IonMacroAssembler.cpp jit/IonSpewer.cpp jit/JSONSpewer.cpp jit/LICM.cpp jit/LIR.cpp jit/LinearScan.cpp jit/LiveRangeAllocator.cpp jit/Lowering.cpp jit/MCallOptimize.cpp jit/MIR.cpp jit/MIRGraph.cpp jit/MoveResolver.cpp jit/ParallelFunctions.cpp jit/ParallelSafetyAnalysis.cpp jit/PerfSpewer.cpp jit/RangeAnalysis.cpp jit/RegisterAllocator.cpp jit/Safepoints.cpp jit/Snapshots.cpp jit/StupidAllocator.cpp jit/TypePolicy.cpp jit/TypeRepresentationSet.cpp jit/UnreachableCodeElimination.cpp jit/VMFunctions.cpp jit/ValueNumbering.cpp jit/shared/Assembler-x86-shared.cpp jit/shared/BaselineCompiler-shared.cpp jit/shared/BaselineCompiler-x86-shared.cpp jit/shared/BaselineIC-x86-shared.cpp jit/shared/CodeGenerator-shared.cpp jit/shared/CodeGenerator-x86-shared.cpp jit/shared/IonFrames-x86-shared.cpp jit/shared/Lowering-shared.cpp jit/shared/Lowering-x86-shared.cpp jit/shared/MoveEmitter-x86-shared.cpp jit/x64/Assembler-x64.cpp jit/x64/Bailouts-x64.cpp jit/x64/BaselineCompiler-x64.cpp jit/x64/BaselineIC-x64.cpp jit/x64/CodeGenerator-x64.cpp jit/x64/Lowering-x64.cpp jit/x64/MacroAssembler-x64.cpp jit/x64/Trampoline-x64.cpp jsalloc.cpp jsanalyze.cpp jsapi.cpp jsbool.cpp jscntxt.cpp jscompartment.cpp jscrashreport.cpp jsdate.cpp jsdtoa.cpp jsexn.cpp jsfriendapi.cpp jsfun.cpp jsgc.cpp jsinfer.cpp jsiter.cpp jsnativestack.cpp jsnum.cpp jsobj.cpp json.cpp jsonparser.cpp jsopcode.cpp jsprf.cpp jspropertytree.cpp jsproxy.cpp jsreflect.cpp jsscript.cpp jsstr.cpp jswatchpoint.cpp jsweakmap.cpp jsworkers.cpp jswrapper.cpp perf/jsperf.cpp prmjtime.cpp vm/ArgumentsObject.cpp vm/CallNonGenericMethod.cpp vm/CharacterEncoding.cpp vm/DateTime.cpp vm/Debugger.cpp vm/ErrorObject.cpp vm/ForkJoin.cpp vm/GlobalObject.cpp vm/Id.cpp vm/Interpreter.cpp vm/MemoryMetrics.cpp vm/Monitor.cpp vm/ObjectImpl.cpp vm/OldDebugAPI.cpp vm/PosixNSPR.cpp vm/Probes.cpp vm/PropertyKey.cpp vm/ProxyObject.cpp vm/RegExpObject.cpp vm/RegExpStatics.cpp vm/Runtime.cpp vm/SPSProfiler.cpp vm/ScopeObject.cpp vm/SelfHosting.cpp vm/Shape.cpp vm/Stack.cpp vm/String.cpp vm/StringBuffer.cpp vm/StructuredClone.cpp vm/ThreadPool.cpp vm/TypedArrayObject.cpp vm/Unicode.cpp vm/Value.cpp vm/Xdr.cpp yarr/PageBlock.cpp yarr/YarrCanonicalizeUCS2.cpp yarr/YarrInterpreter.cpp yarr/YarrPattern.cpp yarr/YarrSyntaxChecker.cpp
LIBRARY_NAME = mozjs-28
