/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef js_confdefs_h
#define js_confdefs_h

#define CPP_THROW_NEW throw()
#define CROSS_COMPILE 1
#define D_INO d_ino
#define EDITLINE 1
#define ENABLE_INTL_API 1
#define ENABLE_YARR_JIT 1
#define EXPOSE_INTL_API 1
#define HAVE_64BIT_OS 1
#define HAVE_ACOSH 1
#define HAVE_ASINH 1
#define HAVE_ATANH 1
#define HAVE_CBRT 1
#define HAVE_CPP_AMBIGUITY_RESOLVING_USING 1
#define HAVE_CPP_DYNAMIC_CAST_TO_VOID_PTR 1
#define HAVE_CPUID_H 1
#define HAVE_DIRENT_H 1
#define HAVE_DLADDR 1
#define HAVE_EXPM1 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_GETC_UNLOCKED 1
#define HAVE_GETOPT_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_HYPOT 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LCHOWN 1
#define HAVE_LIBM 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LOG1P 1
#define HAVE_LOG2 1
#define HAVE_LSTAT64 1
#define HAVE_MACHINE_ENDIAN_H 1
#define HAVE_MBRTOWC 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_RANDOM 1
#define HAVE_SBRK 1
#define HAVE_SETLOCALE 1
#define HAVE_SIGINFO_T 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STAT64 1
#define HAVE_STATVFS 1
#define HAVE_STRERROR 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_TM_ZONE_TM_GMTOFF 1
#define HAVE_TRUNC 1
#define HAVE_UNISTD_H 1
#define HAVE_VA_COPY 1
#define HAVE_VA_LIST_AS_ARRAY 1
#define HAVE_VISIBILITY_ATTRIBUTE 1
#define HAVE_VISIBILITY_HIDDEN_ATTRIBUTE 1
#define HAVE_WCRTOMB 1
#define HAVE__UNWIND_BACKTRACE 1
#define HAVE___CXA_DEMANGLE 1
#define JSGC_INCREMENTAL 1
#define JS_CPU_X64 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define JS_HAVE_MACHINE_ENDIAN_H 1
#define JS_ION 1
#define JS_POSIX_NSPR 1
#define JS_PUNBOX64 1
#define JS_STANDALONE 1
#define JS_STANDALONE 1
#define JS_THREADSAFE 1
#define MOZILLA_UAVERSION "28.0"
#define MOZILLA_UAVERSION "28.0"
#define MOZILLA_VERSION "28.0"
#define MOZILLA_VERSION "28.0"
#define MOZILLA_VERSION_U 28.0
#define MOZILLA_VERSION_U 28.0
#define MOZJS_MAJOR_VERSION 28
#define MOZJS_MAJOR_VERSION 28
#define MOZJS_MINOR_VERSION 0
#define MOZJS_MINOR_VERSION 0
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_DLL_SUFFIX ".dylib"
#define MOZ_UPDATE_CHANNEL default
#define NEED_CPP_UNUSED_IMPLEMENTATIONS 1
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define RELEASE_BUILD 1
#define STDC_HEADERS 1
#define U_STATIC_IMPLEMENTATION 1
#define U_USING_ICU_NAMESPACE 0
#define VA_COPY va_copy
#define XP_MACOSX 1
#define XP_UNIX 1
#define X_DISPLAY_MISSING 1

#include "js/RequiredDefines.h"

#include "mozilla/Char16.h"

#endif /* js_confdefs_h */
