ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = 1
include $(DEPTH)/config/emptyvars.mk
ACDEFINES = -DJS_STANDALONE='1' -DMOZILLA_VERSION='"28.0"' -DMOZILLA_VERSION_U='28.0' -DMOZILLA_UAVERSION='"28.0"' -DMOZJS_MAJOR_VERSION='28' -DMOZJS_MINOR_VERSION='0' -DJS_STANDALONE='1' -DMOZILLA_VERSION='"28.0"' -DMOZILLA_VERSION_U='28.0' -DMOZILLA_UAVERSION='"28.0"' -DMOZJS_MAJOR_VERSION='28' -DMOZJS_MINOR_VERSION='0' -DCROSS_COMPILE='1' -DX_DISPLAY_MISSING='1' -DHAVE_64BIT_OS='1' -DD_INO='d_ino' -DJS_CPU_X64='1' -DJS_PUNBOX64='1' -DJS_ION='1' -DENABLE_YARR_JIT='1' -DMOZ_DEBUG_SYMBOLS='1' -DSTDC_HEADERS='1' -DHAVE_SSIZE_T='1' -DHAVE_ST_BLKSIZE='1' -DHAVE_SIGINFO_T='1' -DHAVE_MACHINE_ENDIAN_H='1' -DJS_HAVE_MACHINE_ENDIAN_H='1' -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE='1' -DHAVE_VISIBILITY_ATTRIBUTE='1' -DHAVE_DIRENT_H='1' -DHAVE_GETOPT_H='1' -DHAVE_MEMORY_H='1' -DHAVE_UNISTD_H='1' -DHAVE_NL_TYPES_H='1' -DHAVE_CPUID_H='1' -DHAVE_SYS_STATVFS_H='1' -DHAVE_SYS_MOUNT_H='1' -DHAVE_SYS_CDEFS_H='1' -DHAVE_DLADDR='1' -DHAVE_FCHMOD='1' -DHAVE_FLOCKFILE='1' -DHAVE_GETC_UNLOCKED='1' -DHAVE_GETPAGESIZE='1' -DHAVE_LCHOWN='1' -DHAVE_LOCALTIME_R='1' -DHAVE_LSTAT64='1' -DHAVE_MEMMOVE='1' -DHAVE_RANDOM='1' -DHAVE_SBRK='1' -DHAVE_SNPRINTF='1' -DHAVE_STAT64='1' -DHAVE_STATVFS='1' -DHAVE_STRERROR='1' -DHAVE_STRTOK_R='1' -DHAVE_LIBM='1' -DHAVE_LOG2='1' -DHAVE_LOG1P='1' -DHAVE_EXPM1='1' -DHAVE_ACOSH='1' -DHAVE_ASINH='1' -DHAVE_ATANH='1' -DHAVE_HYPOT='1' -DHAVE_TRUNC='1' -DHAVE_CBRT='1' -DHAVE_WCRTOMB='1' -DHAVE_MBRTOWC='1' -DHAVE_LANGINFO_CODESET='1' -DVA_COPY='va_copy' -DHAVE_VA_COPY='1' -DHAVE_VA_LIST_AS_ARRAY='1' -DHAVE_CPP_AMBIGUITY_RESOLVING_USING='1' -DHAVE_CPP_DYNAMIC_CAST_TO_VOID_PTR='1' -DNEED_CPP_UNUSED_IMPLEMENTATIONS='1' -DHAVE_I18N_LC_MESSAGES='1' -DHAVE_LOCALECONV='1' -DNS_ATTR_MALLOC='__attribute__((malloc))' -DNS_WARN_UNUSED_RESULT='__attribute__((warn_unused_result))' -DMOZ_UPDATE_CHANNEL='default' -DRELEASE_BUILD='1' -DJS_THREADSAFE='1' -DJS_POSIX_NSPR='1' -DJSGC_INCREMENTAL='1' -DHAVE___CXA_DEMANGLE='1' -DHAVE__UNWIND_BACKTRACE='1' -DJS_DEFAULT_JITREPORT_GRANULARITY='3' -DHAVE_TM_ZONE_TM_GMTOFF='1' -DCPP_THROW_NEW='throw()' -DEDITLINE='1' -DMOZ_DLL_SUFFIX='".dylib"' -DXP_MACOSX='1' -DXP_UNIX='1' -DEXPOSE_INTL_API='1' -DENABLE_INTL_API='1' -DU_STATIC_IMPLEMENTATION='1' -DU_USING_ICU_NAMESPACE='0' -DHAVE_SETLOCALE='1' -DHAVE_LOCALECONV='1'
AR = ar
AR_DELETE = $(AR) d
AR_EXTRACT = $(AR) x
AR_FLAGS = crs $@
AR_LIST = $(AR) t
AS = $(CC)
ASFLAGS =  -fPIC -Wa,--noexecstack
ASM_SUFFIX = s
AS_DASH_C_FLAG = -c
AUTOCONF = :
AWK = awk
CC = /usr/bin/clang
CCACHE = no
CFLAGS = -Qunused-arguments -Wall -Wpointer-arith -Wdeclaration-after-statement -Werror=return-type -Wempty-body -Wsign-compare -Wno-unused -std=gnu99 -fno-common -fno-math-errno -pthread -pipe
CLANG_CXX = 1
COMPILE_ENVIRONMENT = 1
CPP = /usr/bin/clang -E
CPPFLAGS = -Qunused-arguments 
CPU_ARCH = x86_64
CROSS_COMPILE = 1
CROSS_LIB = /usr/x86_64-apple-darwin10.0.0
CXX = /usr/bin/clang++
CXXCPP = /usr/bin/clang++ -E
CXXFLAGS = -Qunused-arguments -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Werror=conversion-null -Wsign-compare -Wno-invalid-offsetof -Wno-c++0x-extensions -Wno-extended-offsetof -Wno-unknown-warning-option -Wno-return-type-c-linkage -Wno-mismatched-tags -fno-common -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe
DEVELOPER_OPTIONS = 1
DLL_PREFIX = lib
DLL_SUFFIX = .dylib
DOXYGEN = :
DSO_PIC_CFLAGS = -fPIC
EDITLINE_LIBS = $(DEPTH)/editline/$(LIB_PREFIX)editline.$(LIB_SUFFIX)
ENABLE_INTL_API = 1
ENABLE_ION = 1
ENABLE_TESTS = 1
ENABLE_YARR_JIT = 1
EXPAND_LIBS_LIST_STYLE = filelist
EXTERNAL_SOURCE_DIR = ../../mfbt
GMAKE = /usr/bin/make
GNU_AS = 1
GNU_CC = 1
GNU_CXX = 1
GRE_MILESTONE = 28.0
HAVE_64BIT_OS = 1
HOST_AR = ar
HOST_AR_FLAGS = crs $@
HOST_CC = cc
HOST_CFLAGS = -DXP_UNIX -DXP_MACOSX -DNO_X11 -MD -MP -MF $(MDDEPDIR)/$(@F).pp
HOST_CXX = c++
HOST_CXXFLAGS = -std=gnu++0x -MD -MP -MF $(MDDEPDIR)/$(@F).pp
HOST_NSPR_MDCPUCFG = \"md/_darwin.cfg\"
HOST_OPTIMIZE_FLAGS = -O3
HOST_OS_ARCH = Darwin
HOST_RANLIB = ranlib
ICU_LIB_NAMES = icui18n icuuc icudata
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INTEL_ARCHITECTURE = 1
JS_CONFIG_NAME = js-config
JS_NATIVE_EDITLINE = 1
JS_POSIX_NSPR = 1
JS_SHARED_LIBRARY = 1
JS_SHELL_NAME = js
JS_STANDALONE = 1
LD = ld
LDFLAGS =   -lobjc
LIBS = -lm 
LIBS_DESC_SUFFIX = desc
LIB_PREFIX = lib
LIB_SUFFIX = a
LN_S = ln -s
MACOSX_DEPLOYMENT_TARGET = 10.6
MKCSHLIB = $(CC) $(CFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -o $@
MKSHLIB = $(CXX) $(CXXFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -o $@
MOZILLA_SYMBOLVERSION = 28
MOZILLA_VERSION = 28.0
MOZJS_MAJOR_VERSION = 28
MOZJS_MINOR_VERSION = 0
MOZ_BUILD_ROOT = /Users/panda/StudyWork/mozilla-release/js/src
MOZ_COMPONENTS_VERSION_SCRIPT_LDFLAGS = -Wl,-exported_symbols_list -Wl,$(BUILD_TOOLS)/gnu-ld-scripts/components-export-list
MOZ_COMPONENT_NSPR_LIBS = -L$(LIBXUL_DIST)/bin $(NSPR_LIBS)
MOZ_DEBUG_DISABLE_DEFS = -DNDEBUG -DTRIMMED
MOZ_DEBUG_ENABLE_DEFS = -DDEBUG -D_DEBUG -DTRACING
MOZ_DEBUG_FLAGS = -g
MOZ_DEBUG_LDFLAGS =  -framework ExceptionHandling
MOZ_DEBUG_SYMBOLS = 1
MOZ_DISABLE_UNIFIED_COMPILATION = 1
MOZ_FIX_LINK_PATHS = -Wl,-executable_path,$(LIBXUL_DIST)/bin
MOZ_FRAMEPTR_FLAGS = -fomit-frame-pointer
MOZ_ICU_LIBS = $(call EXPAND_LIBNAME_PATH,$(ICU_LIB_NAMES),$(DEPTH)/intl/icu/target/lib)
MOZ_ICU_VERSION = 50
MOZ_NATIVE_ZLIB = 1
MOZ_OPTIMIZE = 1
MOZ_OPTIMIZE_FLAGS = -O3 -fno-stack-protector
MOZ_OPTIMIZE_LDFLAGS = -Wl,-dead_strip
MOZ_OS2_HIGH_MEMORY = 1
MOZ_PSEUDO_DERECURSE = no-pymake
MOZ_UPDATE_CHANNEL = default
MOZ_ZLIB_LIBS =  -lz
NO_LD_ARCHIVE_FLAGS = 1
NSPR_PKGCONF_CHECK = nspr
OBJ_SUFFIX = o
OS_ARCH = Darwin
OS_CFLAGS = -Qunused-arguments -Wall -Wpointer-arith -Wdeclaration-after-statement -Werror=return-type -Wempty-body -Wsign-compare -Wno-unused -std=gnu99 -fno-common -fno-math-errno -pthread -pipe
OS_COMPILE_CFLAGS = -include $(DEPTH)/js-confdefs.h -DMOZILLA_CLIENT -MD -MP -MF $(MDDEPDIR)/$(@F).pp
OS_COMPILE_CXXFLAGS = -DMOZILLA_CLIENT -include $(DEPTH)/js-confdefs.h -MD -MP -MF $(MDDEPDIR)/$(@F).pp
OS_CPPFLAGS = -Qunused-arguments 
OS_CXXFLAGS = -Qunused-arguments -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Werror=conversion-null -Wsign-compare -Wno-invalid-offsetof -Wno-c++0x-extensions -Wno-extended-offsetof -Wno-unknown-warning-option -Wno-return-type-c-linkage -Wno-mismatched-tags -fno-common -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe
OS_LDFLAGS =   -lobjc
OS_LIBS = -lm 
OS_TARGET = Darwin
OS_TEST = x86_64
PERL = /usr/bin/perl
PROFILE_GEN_CFLAGS = -fprofile-generate
PROFILE_GEN_LDFLAGS = -fprofile-generate
PROFILE_USE_CFLAGS = -fprofile-use -fprofile-correction -Wcoverage-mismatch
PROFILE_USE_LDFLAGS = -fprofile-use
PYTHON = /Users/panda/StudyWork/mozilla-release/js/src/_virtualenv/bin/python
PYTHON_SITE_PACKAGES = /Users/panda/StudyWork/mozilla-release/js/src/_virtualenv/lib/python2.7/site-packages
RANLIB = ranlib
RELEASE_BUILD = 1
SHELL = /bin/sh
STRIP = strip -x -S
TAR = tar
TARGET_CPU = x86_64
TARGET_MD_ARCH = unix
TARGET_NSPR_MDCPUCFG = \"md/_darwin.cfg\"
TARGET_OS = darwin10.0.0
TARGET_VENDOR = apple
TARGET_XPCOM_ABI = x86_64-gcc3
TOP_DIST = dist
USE_DEPENDENT_LIBS = 1
VISIBILITY_FLAGS = -fvisibility=hidden
WINDRES = :
XARGS = /usr/bin/xargs
ac_configure_args =  --target=x86_64-apple-darwin10.0.0
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin13.1.0
build_alias = x86_64-apple-darwin13.1.0
build_cpu = x86_64
build_os = darwin13.1.0
build_vendor = apple
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = x86_64-apple-darwin13.1.0
host_alias = x86_64-apple-darwin13.1.0
host_cpu = x86_64
host_os = darwin13.1.0
host_vendor = apple
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = x86_64-apple-darwin10.0.0
target_alias = x86_64-apple-darwin10.0.0
target_cpu = x86_64
target_os = darwin10.0.0
target_vendor = apple
top_srcdir = .
include $(topsrcdir)/config/baseconfig.mk
endif
