# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

MOZBUILD_DERIVED := 1
DEFINES += -DMOZ_NATIVE_ZLIB=1
HOST_PROGRAM = nsinstall_real
HOST_CSRCS += nsinstall.c
HOST_CSRCS += pathsub.c
NO_DIST_INSTALL := 1
VISIBILITY_FLAGS := 
