# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

MOZBUILD_DERIVED := 1
DEFINES += -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY
FORCE_STATIC_LIB := 1
CSRCS += editline.c sysunix.c
LIBRARY_NAME = editline
